sudo: required
services:
  - docker

before_install:
  - docker build -t prasadadda/docker-react -f Dockerfile.dev .
script:
  - docker run prasadadda/docker-react npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "<<S3 Biucket>>"
    bucker_path: "docker"
    on:
      branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"


